// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXyw86aozrpIioEwboW0a0yxBcVowQRmI',
    appId: '1:1042678564340:web:420f2be2d9bcf98510e5a1',
    messagingSenderId: '1042678564340',
    projectId: 'fixnow-dd022',
    authDomain: 'fixnow-dd022.firebaseapp.com',
    storageBucket: 'fixnow-dd022.firebasestorage.app',
    measurementId: 'G-L4KR04R11K',
  );
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDG6oWTjFazuE_elY74m7qogYjDM2gE1Y8',
    appId: '1:1042678564340:android:7f040e1a9346f86f10e5a1',
    messagingSenderId: '1042678564340',
    projectId: 'fixnow-dd022',
    storageBucket: 'fixnow-dd022.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkx8YRS3HtvoLn4yXYb-UGT6EXg16NQjQ',
    appId: '1:1042678564340:ios:593a1660659685f010e5a1',
    messagingSenderId: '1042678564340',
    projectId: 'fixnow-dd022',
    storageBucket: 'fixnow-dd022.firebasestorage.app',
    iosBundleId: 'com.fixnow.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkx8YRS3HtvoLn4yXYb-UGT6EXg16NQjQ',
    appId: '1:1042678564340:ios:593a1660659685f010e5a1',
    messagingSenderId: '1042678564340',
    projectId: 'fixnow-dd022',
    storageBucket: 'fixnow-dd022.firebasestorage.app',
    iosBundleId: 'com.fixnow.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXyw86aozrpIioEwboW0a0yxBcVowQRmI',
    appId: '1:1042678564340:web:03841d0ad98410e710e5a1',
    messagingSenderId: '1042678564340',
    projectId: 'fixnow-dd022',
    authDomain: 'fixnow-dd022.firebaseapp.com',
    storageBucket: 'fixnow-dd022.firebasestorage.app',
    measurementId: 'G-NP8NFZ8Z13',
  );
}
